# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resCountry', models.CharField(max_length=255, verbose_name='Residence Country')),
                ('resRegion', models.CharField(max_length=255, verbose_name='Residence Region')),
                ('resCity', models.CharField(max_length=255, verbose_name='Residence City')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Resident Info',
                'verbose_name_plural': 'Resident Infos',
            },
        ),
    ]
