# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityCardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identityCardNumber', models.CharField(max_length=9, verbose_name='Identity Card Number')),
                ('issuedBy', models.CharField(max_length=255, verbose_name='Issued By')),
                ('dateOfIssue', models.DateField(verbose_name='Date of Issue')),
            ],
            options={
                'verbose_name': 'Identity Card Info',
                'verbose_name_plural': 'Identity Card Infos',
            },
        ),
    ]
