# Generated by Django 4.2.7 on 2023-11-02 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_card_info', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycardinfo',
            name='identityCardNumber',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
