# Generated by Django 4.2.7 on 2023-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity_card_info', '0002_alter_identitycardinfo_identitycardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identitycardinfo',
            name='identityCardNumber',
            field=models.IntegerField(),
        ),
    ]
