# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rankTitle', models.CharField(max_length=255, verbose_name='Rank Title')),
                ('order', models.IntegerField(verbose_name='Order')),
                ('pensionAge', models.IntegerField(default=48, verbose_name='PensionAge')),
                ('nextPromotionDateInDays', models.IntegerField(default=1, null=True, verbose_name='Next Promotion Date in Days')),
            ],
            options={
                'verbose_name': 'Military Rank',
                'verbose_name_plural': 'Military Ranks',
            },
        ),
        migrations.CreateModel(
            name='RankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedType', models.CharField(max_length=255, verbose_name='Received Type')),
                ('decreeNumber', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Decree Number')),
                ('receivedDate', models.DateField(verbose_name='Received Date')),
                ('nextPromotionDate', models.DateField(blank=True, null=True, verbose_name='Next Promotion Date')),
                ('needPositionUp', models.BooleanField(default=False, verbose_name='Need Position Up')),
                ('militaryRank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military_rank.militaryrank', verbose_name='Military Rank')),
            ],
            options={
                'verbose_name': 'Rank Info',
                'verbose_name_plural': 'Rank Infos',
            },
        ),
    ]
