# Generated by Django 4.2.7 on 2023-11-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_autobiography_autobiographyimage_and_more'),
        ('military_rank', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rankinfo',
            name='militaryRank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military_rank.militaryrank'),
        ),
        migrations.AlterField(
            model_name='rankinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
