# Generated by Django 4.2.7 on 2023-11-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('military_rank', '0002_alter_militaryrank_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='militaryrank',
            name='nextPromotionDate',
        ),
    ]
