# Generated by Django 4.2.7 on 2023-11-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military_rank', '0003_remove_militaryrank_nextpromotiondate'),
    ]

    operations = [
        migrations.AddField(
            model_name='militaryrank',
            name='nextPromotionDateInDays',
            field=models.IntegerField(default=1),
        ),
    ]
