# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirthInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('region', models.CharField(max_length=255, verbose_name='Регион')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Информация о дате рождения',
                'verbose_name_plural': 'Информации о дате рождения',
            },
        ),
    ]
