# Generated by Django 4.2.7 on 2023-11-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birth_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='birthinfo',
            old_name='district',
            new_name='city',
        ),
    ]
