# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('birth_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='ИИН Сотрудника'),
        ),
    ]
