# Generated by Django 4.2.7 on 2023-11-06 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_birthinfoid_and_more'),
        ('birth_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
