# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicPlace', models.CharField(max_length=255, verbose_name='Academic Place')),
                ('academicDegree', models.CharField(max_length=255, verbose_name='Academic Degree')),
                ('academicDiplomaNumber', models.CharField(max_length=255, verbose_name='Academic Diploma Number')),
                ('academicDiplomaDate', models.DateField(verbose_name='Academic Diploma Date')),
            ],
            options={
                'verbose_name': 'Academic Degree',
                'verbose_name_plural': 'Academic Degrees',
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attResult', models.CharField(max_length=255, verbose_name='Attestation Result')),
                ('lastAttDate', models.DateField(verbose_name='Last Attestation Date')),
                ('nextAttDateMin', models.DateField(blank=True, null=True, verbose_name='Next Attestation Date (Min)')),
                ('nextAttDateMax', models.DateField(blank=True, null=True, verbose_name='Next Attestation Date (Max)')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255, verbose_name='Course Name')),
                ('courseType', models.CharField(max_length=255, verbose_name='Course Type')),
                ('courseOrg', models.CharField(max_length=255, verbose_name='Course Organization')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(verbose_name='End Date')),
                ('documentType', models.CharField(max_length=255, verbose_name='Document Type')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationType', models.CharField(max_length=255, verbose_name='Education Type')),
                ('educationPlace', models.CharField(max_length=255, verbose_name='Education Place')),
                ('educationDateIn', models.DateField(verbose_name='Education Start Date')),
                ('educationDateOut', models.DateField(verbose_name='Education End Date')),
                ('speciality', models.CharField(max_length=255, verbose_name='Speciality')),
                ('educationForm', models.CharField(default='Очное', max_length=255, verbose_name='educationForm')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
    ]
