# Generated by Django 4.2.7 on 2023-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicPlace', models.CharField(max_length=255)),
                ('academicDegree', models.CharField(max_length=255)),
                ('academicDiplomaNumber', models.CharField(max_length=255)),
                ('academicDiplomaDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attResult', models.CharField(max_length=255)),
                ('lastAttDate', models.DateField()),
                ('nextAttDateMin', models.DateField()),
                ('nextAttDateMax', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=255)),
                ('courseType', models.CharField(max_length=255)),
                ('courseOrg', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('documentType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educationType', models.CharField(max_length=255)),
                ('educationPlace', models.CharField(max_length=255)),
                ('educationDateIn', models.DateField()),
                ('educationDateOut', models.DateField()),
                ('speciality', models.CharField(max_length=255)),
                ('diplomaNumber', models.CharField(max_length=255)),
            ],
        ),
    ]
