# Generated by Django 4.2.7 on 2023-11-03 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
        migrations.AddField(
            model_name='course',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
        migrations.AddField(
            model_name='attestation',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
    ]
