# Generated by Django 4.2.7 on 2023-11-03 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('education', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicDegree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academicPlace', models.CharField(max_length=255)),
                ('academicDegree', models.CharField(max_length=255)),
                ('academicDiplomaNumber', models.CharField(max_length=255)),
                ('academicDiplomaDate', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
    ]
