# Generated by Django 4.2.7 on 2023-11-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('education', '0003_academicdegree'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdegree',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='course',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='education',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
