# Generated by Django 4.2.7 on 2026-07-08 08:00

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('military_rank', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=255, verbose_name='Status Name')),
            ],
            options={
                'verbose_name': 'FamilyStatus',
                'verbose_name_plural': 'FamilyStatuses',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderName', models.CharField(max_length=255, verbose_name='Gender Name')),
            ],
            options={
                'verbose_name': 'Gender',
                'verbose_name_plural': 'Genders',
            },
        ),
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holidayDate', models.DateField(default=None, verbose_name='Holiday date')),
                ('holidayTitle', models.CharField(max_length=255, verbose_name='Holiday title')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12, verbose_name='IIN')),
                ('pin', models.CharField(max_length=255, verbose_name='PIN')),
                ('surname', models.CharField(max_length=255, verbose_name='Surname')),
                ('firstName', models.CharField(max_length=255, verbose_name='First Name')),
                ('patronymic', models.CharField(max_length=255, verbose_name='Patronymic')),
                ('nationality', models.CharField(max_length=255, verbose_name='Nationality')),
                ('isFired', models.BooleanField(default=False, verbose_name='isFired')),
                ('inVacation', models.BooleanField(default=False, verbose_name='inVacation')),
                ('inKomandirovka', models.BooleanField(default=False, verbose_name='inKomandirovka')),
                ('role', models.CharField(default='User', max_length=255, verbose_name='Role')),
                ('familyStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.familystatus', verbose_name='Family Status')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.gender', verbose_name='Gender')),
                ('positionInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.positioninfo', verbose_name='Position Info')),
                ('rankInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='military_rank.rankinfo', verbose_name='Rank Info')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relativeName', models.CharField(max_length=255, verbose_name='Relative Name')),
            ],
            options={
                'verbose_name': 'Relative',
                'verbose_name_plural': 'Relatives',
            },
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2026, verbose_name='Vacation year')),
                ('daysType', models.CharField(default='Обычные', verbose_name='Vacation days type')),
                ('daysCount', models.IntegerField(default=0, verbose_name='Vacation days count')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Vacation',
                'verbose_name_plural': 'Vacations',
            },
        ),
        migrations.CreateModel(
            name='SportSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportType', models.CharField(max_length=255, verbose_name='Sport Type')),
                ('sportSkillLvl', models.CharField(max_length=255, verbose_name='Sport Skill Level')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'SportSkill',
                'verbose_name_plural': 'SportSkills',
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardType', models.CharField(max_length=255, verbose_name='Reward Type')),
                ('rewardDocNumber', models.CharField(max_length=255, verbose_name='Reward Document Number')),
                ('rewardDate', models.DateField(verbose_name='Reward Date')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
            },
        ),
        migrations.CreateModel(
            name='RankArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedType', models.CharField(max_length=255, verbose_name='Received Type')),
                ('decreeNumber', models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Decree Number')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('militaryRank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='military_rank.militaryrank', verbose_name='Military Rank')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'RankArchive',
                'verbose_name_plural': 'RankArchives',
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langName', models.CharField(max_length=255, verbose_name='Language Name')),
                ('skillLvl', models.CharField(max_length=255, verbose_name='Language Skill Level')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'LanguageSkill',
                'verbose_name_plural': 'LanguageSkills',
            },
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relName', models.CharField(max_length=255, verbose_name='Relative Name')),
                ('relSurname', models.CharField(max_length=255, verbose_name='Relative Surname')),
                ('relPatronymic', models.CharField(max_length=255, verbose_name='Relative Patronymic')),
                ('relIin', models.CharField(max_length=12, verbose_name='Relative IIN')),
                ('relBirthDate', models.DateField(verbose_name='Relative Birth Date')),
                ('relJobPlace', models.CharField(max_length=255, verbose_name='Relative Job Place')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
                ('relativeType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.relative', verbose_name='Relative Type')),
            ],
            options={
                'verbose_name': 'FamilyComposition',
                'verbose_name_plural': 'FamilyCompositions',
            },
        ),
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(max_length=255, verbose_name='Category Type')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'ClassCategory',
                'verbose_name_plural': 'ClassCategories',
            },
        ),
        migrations.CreateModel(
            name='Autobiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autobiographyText', models.CharField(max_length=2096, null=True, verbose_name='Autobiography Text')),
                ('autobiographyImage', models.TextField(null=True, verbose_name='Autobiography Image')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Autobiography',
                'verbose_name_plural': 'Autobiographies',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('person_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='vacation',
            constraint=models.UniqueConstraint(fields=('year', 'daysType', 'personId'), name='unique_vacation'),
        ),
    ]
