# Generated by Django 4.2.7 on 2023-11-02 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity_card_info', '0004_alter_identitycardinfo_identitycardnumber'),
        ('location', '0001_initial'),
        ('resident_info', '0001_initial'),
        ('photo', '0001_initial'),
        ('birth_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genderName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iin', models.CharField(max_length=12)),
                ('pin', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('firstName', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('birthInfoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='birth_info.birthinfo')),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.department')),
                ('familyStatus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.familystatus')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.gender')),
                ('identityCardInfoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identity_card_info.identitycardinfo')),
                ('photoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photo.photo')),
                ('residentInfoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resident_info.residentinfo')),
            ],
        ),
    ]
