# Generated by Django 4.2.7 on 2023-11-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birthInfoId',
        ),
        migrations.RemoveField(
            model_name='person',
            name='identityCardInfoId',
        ),
        migrations.RemoveField(
            model_name='person',
            name='photoId',
        ),
        migrations.RemoveField(
            model_name='person',
            name='residentInfoId',
        ),
    ]
