# Generated by Django 4.2.7 on 2023-11-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('identity_card_info', '0001_initial'),
        ('resident_info', '0001_initial'),
        ('location', '0001_initial'),
        ('photo', '0001_initial'),
        ('birth_info', '0002_rename_district_birthinfo_city'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobiography',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='classcategory',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='familycomposition',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='languageskill',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthInfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='birth_info.birthinfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='departmentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.department'),
        ),
        migrations.AlterField(
            model_name='person',
            name='familyStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.familystatus'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.gender'),
        ),
        migrations.AlterField(
            model_name='person',
            name='identityCardInfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity_card_info.identitycardinfo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='photoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photo.photo'),
        ),
        migrations.AlterField(
            model_name='person',
            name='residentInfoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resident_info.residentinfo'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='sportskill',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
