# Generated by Django 4.2.7 on 2023-11-02 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relativeName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SportSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportType', models.CharField(max_length=255)),
                ('sportSkillLvl', models.CharField(max_length=255)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rewardType', models.CharField(max_length=255)),
                ('rewardDocNumber', models.CharField(max_length=255)),
                ('rewardDate', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langName', models.CharField(max_length=255)),
                ('skillLvl', models.CharField(max_length=255)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relName', models.CharField(max_length=255)),
                ('relSurname', models.CharField(max_length=255)),
                ('relPatronymic', models.CharField(max_length=255)),
                ('relIin', models.CharField(max_length=12)),
                ('relBirthDate', models.DateField()),
                ('relJobPlace', models.CharField(max_length=255)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
                ('relativeTypeId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.relative')),
            ],
        ),
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryType', models.CharField(max_length=255)),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='Autobiography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autobiographyText', models.CharField(max_length=2096)),
                ('autobiographyImage', models.TextField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
    ]
