# Generated by Django 4.2.7 on 2023-11-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_birthinfoid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autobiography',
            name='autobiographyImage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='autobiography',
            name='autobiographyText',
            field=models.CharField(max_length=2096, null=True),
        ),
    ]
