# Generated by Django 4.2.7 on 2023-11-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_alter_autobiography_autobiographyimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(default='User', max_length=255),
        ),
    ]
