# Generated by Django 4.2.7 on 2023-11-09 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField(null=True)),
                ('department', models.CharField(max_length=255, null=True)),
                ('organizationName', models.CharField(max_length=255)),
                ('organizationAddress', models.CharField(max_length=492, null=True)),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
