# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=255, verbose_name='Position Name')),
                ('startDate', models.DateField(verbose_name='Start Date')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('department', models.CharField(max_length=255, null=True, verbose_name='Department')),
                ('organizationName', models.CharField(max_length=255, verbose_name='Organization Name')),
                ('organizationAddress', models.CharField(max_length=492, null=True, verbose_name='Organization Address')),
                ('isPravoOhranka', models.BooleanField(default=False, verbose_name='Is Pravo Ohranka')),
                ('HaveCoefficient', models.BooleanField(default=False, verbose_name='Have Coefficient')),
                ('personType', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='personType')),
                ('personSubType', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='personSubType')),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Working History',
                'verbose_name_plural': 'Working Histories',
            },
        ),
    ]
