# Generated by Django 4.2.7 on 2023-11-10 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position')),
            ],
        ),
    ]
