# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_date', models.DateField(verbose_name='Available Date')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.department', verbose_name='Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Vacancy',
                'verbose_name_plural': 'Vacancies',
            },
        ),
        migrations.CreateModel(
            name='StaffingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_counter', models.IntegerField(default=0)),
                ('current_count', models.IntegerField(default=0, verbose_name='Current Count')),
                ('max_count', models.IntegerField(verbose_name='Max Count')),
                ('staffing_table_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.department', verbose_name='Department')),
                ('staffing_table_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position', verbose_name='Position')),
                ('vacancy_list', models.ManyToManyField(blank=True, to='staffing_table.vacancy', verbose_name='Vacancy List')),
            ],
            options={
                'verbose_name': 'Staffing Table',
                'verbose_name_plural': 'Staffing Tables',
            },
        ),
    ]
