# Generated by Django 4.2.7 on 2023-11-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffing_table', '0002_rename_count_staffingtable_current_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffingtable',
            name='current_count',
            field=models.IntegerField(default=0),
        ),
    ]
