# Generated by Django 4.2.7 on 2023-11-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('person', '0001_initial'),
        ('military_rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=255)),
                ('order', models.IntegerField(null=True)),
                ('departmentId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location.department')),
                ('maxRank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='military_rank.militaryrank')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('department', models.CharField(max_length=255, null=True)),
                ('organizationName', models.CharField(max_length=255)),
                ('organizationAddress', models.CharField(max_length=492, null=True)),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedDate', models.DateField()),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position')),
            ],
        ),
    ]
