# Generated by Django 4.2.7 on 2023-11-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('military_rank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('maxRank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='military_rank.militaryrank')),
            ],
        ),
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedDate', models.DateField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='position.position')),
            ],
        ),
    ]
