# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('military_rank', '0001_initial'),
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionTitle', models.CharField(max_length=255, verbose_name='Position Title')),
                ('positionTitleKaz', models.CharField(default='Жедел уәкіл', max_length=255, verbose_name='Position Title Kaz')),
                ('order', models.IntegerField(null=True, verbose_name='Order')),
                ('maxRank', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='military_rank.militaryrank', verbose_name='Max Rank')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedDate', models.DateField(verbose_name='Received Date')),
                ('department', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.department', verbose_name='Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Position Info',
                'verbose_name_plural': 'Position Infos',
            },
        ),
    ]
