# Generated by Django 4.2.7 on 2023-11-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positioninfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
    ]
