# Generated by Django 4.2.7 on 2023-11-06 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_alter_autobiography_personid_and_more'),
        ('location', '0001_initial'),
        ('military_rank', '0002_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='departmentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='location.department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='maxRank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='military_rank.militaryrank'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position'),
        ),
        migrations.AlterField(
            model_name='workinghistory',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person'),
        ),
    ]
