# Generated by Django 4.2.7 on 2023-11-02 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('position', '0002_positioninfo_personid'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='departmentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='location.department'),
        ),
        migrations.AlterField(
            model_name='position',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
