# Generated by Django 4.2.7 on 2023-11-02 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_relative_sportskill_reward_languageskill_and_more'),
        ('position', '0003_position_departmentid_alter_position_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=255)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('department', models.CharField(max_length=255, null=True)),
                ('organizationName', models.CharField(max_length=255)),
                ('organizationAddress', models.CharField(max_length=492, null=True)),
                ('personId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
    ]
