# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentProbation', models.IntegerField(blank=True, null=True, verbose_name='Appointment Probation')),
                ('appointmentType', models.CharField(default='None', max_length=255, verbose_name='Appointment Type')),
            ],
            options={
                'verbose_name': 'AppointmentInfo',
                'verbose_name_plural': 'AppointmentInfos',
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseName', models.CharField(max_length=255, verbose_name='baseName')),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.CreateModel(
            name='DecreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreeType', models.CharField(max_length=255, verbose_name='Decree Type')),
                ('decreeNumber', models.CharField(blank=True, max_length=255, null=True, verbose_name='Decree Number')),
                ('decreeDate', models.DateField(verbose_name='Decree Date')),
                ('isConfirmed', models.BooleanField(default=False, verbose_name='isConfirmed')),
                ('minioDocName', models.CharField(blank=True, default='None', max_length=4048, null=True, verbose_name='minioDocName')),
            ],
            options={
                'verbose_name': 'Decree List',
                'verbose_name_plural': 'Decree Lists',
            },
        ),
        migrations.CreateModel(
            name='FiringInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firingDate', models.DateField(blank=True, null=True, verbose_name='Firing date')),
            ],
            options={
                'verbose_name': 'FiringInfo',
                'verbose_name_plural': 'FiringInfos',
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_decree_type', models.CharField(max_length=255, verbose_name='Investigation Decree Type')),
                ('investigation_decree_number', models.CharField(max_length=255, verbose_name='Investigation Decree Number')),
                ('investigation_date', models.DateField(verbose_name='Investigation Date')),
            ],
            options={
                'verbose_name': 'Investigation',
                'verbose_name_plural': 'Investigations',
            },
        ),
        migrations.CreateModel(
            name='KomandirovkaInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(verbose_name='Komandirovka start date')),
                ('endDate', models.DateField(verbose_name='Komandirovka end date')),
                ('departure', models.CharField(max_length=255, verbose_name='Departure')),
                ('travelChoice', models.CharField(max_length=255, verbose_name='Travel choice')),
                ('transport', models.CharField(max_length=255, verbose_name='Transport')),
            ],
            options={
                'verbose_name': 'KomandirovkaInfo',
                'verbose_name_plural': 'KomandirovkaInfos',
            },
        ),
        migrations.CreateModel(
            name='OtpuskInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField(blank=True, null=True, verbose_name='Otpusk start date')),
                ('endDate', models.DateField(blank=True, null=True, verbose_name='Otpusk end date')),
                ('otpuskType', models.CharField(max_length=255, verbose_name='Otpusk type')),
                ('benefitChoice', models.CharField(blank=True, max_length=255, null=True, verbose_name='Benefit choice')),
                ('otzivDate', models.DateField(blank=True, null=True, verbose_name='Otpusk otziv date')),
                ('oldBasicDaysCount', models.IntegerField(blank=True, null=True, verbose_name='Old basic days')),
                ('oldExperiencedDaysCount', models.IntegerField(blank=True, null=True, verbose_name='Old experienced days')),
                ('newBasicDaysCount', models.IntegerField(blank=True, null=True, verbose_name='New basic days')),
                ('newExperiencedDaysCount', models.IntegerField(blank=True, null=True, verbose_name='New experienced days')),
            ],
            options={
                'verbose_name': 'OtpuskInfo',
                'verbose_name_plural': 'OtpuskInfos',
            },
        ),
        migrations.CreateModel(
            name='RankUpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receivedType', models.CharField(max_length=255, verbose_name='Received Type')),
                ('receivedDate', models.DateField(blank=True, null=True, verbose_name='Received Date')),
            ],
            options={
                'verbose_name': 'RankUpInfo',
                'verbose_name_plural': 'RankUpInfos',
            },
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickDocNumber', models.CharField(max_length=255, verbose_name='Sick Document Number')),
                ('sickDocDate', models.DateField(verbose_name='Sick Document Date')),
            ],
            options={
                'verbose_name': 'Sick Leave',
                'verbose_name_plural': 'Sick Leaves',
            },
        ),
        migrations.CreateModel(
            name='SpecCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNumber', models.CharField(max_length=255, verbose_name='Document Number')),
                ('docDate', models.DateField(verbose_name='Document Date')),
            ],
            options={
                'verbose_name': 'Spec Check',
                'verbose_name_plural': 'Spec Checks',
            },
        ),
        migrations.CreateModel(
            name='TransferInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreeId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decree.decreelist', verbose_name='Decree id')),
                ('newDepartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_transfer_infos', to='location.department', verbose_name='New Department')),
                ('newPosition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_transfer_infos', to='position.position', verbose_name='New Position')),
            ],
            options={
                'verbose_name': 'TransferInfo',
                'verbose_name_plural': 'TransferInfos',
            },
        ),
    ]
