# Generated by Django 4.2.7 on 2023-11-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreeType', models.CharField(max_length=255)),
                ('decreeSubType', models.CharField(max_length=255)),
                ('decreeDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickDocNumber', models.CharField(max_length=255)),
                ('sickDocDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SpecCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNumber', models.CharField(max_length=255)),
                ('docDate', models.DateField()),
            ],
        ),
    ]
