# Generated by Django 4.2.7 on 2023-11-02 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0002_relative_sportskill_reward_languageskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docNumber', models.CharField(max_length=255)),
                ('docDate', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='SickLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sickDocNumber', models.CharField(max_length=255)),
                ('sickDocDate', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
        migrations.CreateModel(
            name='DecreeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decreeType', models.CharField(max_length=255)),
                ('decreeSubType', models.CharField(max_length=255)),
                ('decreeDate', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
    ]
