# Generated by Django 4.2.7 on 2023-11-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('decree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='speccheck',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
        migrations.AddField(
            model_name='decreelist',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person'),
        ),
    ]
