# Generated by Django 4.2.7 on 2026-07-08 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('decree', '0001_initial'),
        ('location', '0001_initial'),
        ('position', '0001_initial'),
        ('military_rank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='transferinfo',
            name='previousDepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_transfer_infos', to='location.department', verbose_name='Previous Department'),
        ),
        migrations.AddField(
            model_name='transferinfo',
            name='previousPosition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_transfer_infos', to='position.position', verbose_name='Previous Position'),
        ),
        migrations.AddField(
            model_name='speccheck',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='sickleave',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='rankupinfo',
            name='decreeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decree.decreelist', verbose_name='Decree id'),
        ),
        migrations.AddField(
            model_name='rankupinfo',
            name='newRank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_rank_up_infos', to='military_rank.militaryrank', verbose_name='New Rank'),
        ),
        migrations.AddField(
            model_name='rankupinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='rankupinfo',
            name='previousRank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_rank_up_infos', to='military_rank.militaryrank', verbose_name='Previous Rank'),
        ),
        migrations.AddField(
            model_name='otpuskinfo',
            name='decreeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decree.decreelist', verbose_name='Decree id'),
        ),
        migrations.AddField(
            model_name='otpuskinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='komandirovkainfo',
            name='decreeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decree.decreelist', verbose_name='Decree id'),
        ),
        migrations.AddField(
            model_name='komandirovkainfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='investigation',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='firinginfo',
            name='decreeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decree.decreelist', verbose_name='Decree id'),
        ),
        migrations.AddField(
            model_name='firinginfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='decreelist',
            name='decreeBases',
            field=models.ManyToManyField(blank=True, to='decree.base', verbose_name='Bases'),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='appointmentDepartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.department', verbose_name='Appointment Department'),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='appointmentPosition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='position.position', verbose_name='Appointment Position'),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='decreeId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='decree.decreelist', verbose_name='Decree id'),
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
    ]
