# Generated by Django 4.2.7 on 2023-11-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_remove_person_birthinfoid_and_more'),
        ('decree', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation_decree_type', models.CharField(max_length=255)),
                ('investigation_decree_number', models.CharField(max_length=255)),
                ('investigation_date', models.DateField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
        ),
    ]
