# Generated by Django 4.2.7 on 2024-01-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decree', '0010_appointmentinfo_appointmenttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentinfo',
            name='appointmentProbation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Appointment Probation'),
        ),
    ]
