# Generated by Django 4.2.7 on 2024-02-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decree', '0010_alter_otpuskinfo_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpuskinfo',
            name='otzivDate',
            field=models.DateField(blank=True, null=True, verbose_name='Otpusk otziv date'),
        ),
    ]
