# Generated by Django 4.2.7 on 2024-02-14 05:23

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_person_inkomandirovka_person_invacation'),
        ('decree', '0011_otpuskinfo_otzivdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentinfo',
            name='appointmentBase',
        ),
        migrations.RemoveField(
            model_name='decreelist',
            name='personIds',
        ),
        migrations.RemoveField(
            model_name='transferinfo',
            name='transferBase',
        ),
        migrations.AddField(
            model_name='appointmentinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='decreelist',
            name='decreeBases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='decreeBases'),
        ),
        migrations.AddField(
            model_name='komandirovkainfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='otpuskinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='rankupinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
        migrations.AddField(
            model_name='transferinfo',
            name='personId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='person.person', verbose_name='Person id'),
        ),
    ]
