# Generated by Django 4.2.7 on 2024-02-14 05:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decree', '0012_remove_appointmentinfo_appointmentbase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decreelist',
            name='decreeBases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
    ]
