# Generated by Django 4.2.7 on 2024-02-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decree', '0013_alter_decreelist_decreebases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseName', models.CharField(max_length=255, verbose_name='baseName')),
            ],
            options={
                'verbose_name': 'Base',
                'verbose_name_plural': 'Bases',
            },
        ),
        migrations.RemoveField(
            model_name='decreelist',
            name='decreeBases',
        ),
        migrations.AddField(
            model_name='decreelist',
            name='decreeBases',
            field=models.ManyToManyField(to='decree.base', verbose_name='Bases'),
        ),
    ]
