# Generated by Django 4.2.7 on 2024-02-14 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decree', '0014_base_remove_decreelist_decreebases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decreelist',
            name='decreeBases',
            field=models.ManyToManyField(blank=True, null=True, to='decree.base', verbose_name='Bases'),
        ),
    ]
